heat_template_version: 2021-04-16
description: >
  This template demonstrates the different ways configuration resources
  can be used to specify boot-time cloud-init configuration.
parameters:
  key_name:
    type: string
    default: controller-key
  flavor:
    type: string
    default: m1.medium.kube
  image:
    type: string
    default: jammy-server-cloudimg-amd64
  internal-network-id:
    type: string
    default: 94a28163-a6f2-405c-8c00-57c831f68e58
  master-ip:
    type: string
    default: 192.168.100.201
  master-token:
    type: string
    default: MASTER-TOKEN
  master-token-ca-cert-hash:
    type: string
    default: MASTER-TOKEN-CA-CERT-HASH

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      image: {get_param: image}
      flavor: {get_param: flavor}
      security_groups:
      - security-group-allow-ssh-icmp-kube
      key_name: {get_param: key_name}
      networks:
      - network: {get_param: internal-network-id} #internal-net-loki id
#      user_data_format: SOFTWARE_CONFIG
      user_data_format: RAW
      user_data: |
        #!/bin/sh
        cat /proc/cpuinfo > /tmp/cpuinfo.log
        echo "message" > /home/ubuntu/message.txt
        swapon -s
        sudo swapoff -a
        sudo apt install socat -y
        sudo kubeadm join ${master-ip}:6443 --token ${master-token} --discovery-token-ca-cert-hash sha256:${master-token-ca-cert-hash}


  ps_script:
    type: OS::Heat::SoftwareConfig
    properties:
      config: |
        #!/bin/bash
        swapon -s
        sudo swapoff -a
        sudo apt install socat -y
        sudo kubeadm join ${master-ip}:6443 --token ${master-token} --discovery-token-ca-cert-hash sha256:${master-token-ca-cert-hash}


  deployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      config: {get_resource: ps_script}
      server: {get_resource: my_instance }

outputs:
  instance_name:
    description: "Name of the instance"
    value: { get_attr: [ my_instance, name ] }
#  result:
#    description: Check output
#    value: { get_attr: [deployment, name] }
#  instance_metadata:
#    description: "The metadata of the created instance"
#    value: { get_param: [ my_instance, metadata ] }
#  instance_address:
#    description: "The hostname of the created instance"
#    value: { get_attr: [ my_instance, first_address ] }
