apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webserver
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
#  targetCPUUtilizationPercentage: 70
