[DEFAULT]
debug = False
log_dir = /var/log/kolla/ceilometer
transport_url = rabbit://openstack:pY4CVoHILUo18qUzra4gTRRvyZXWPZoDYcNUPXBj@192.168.99.91:5672//

[service_credentials]
auth_url = http://192.168.99.200:5000
region_name = RegionOne
password = vaj379H5Qk5cUpM8ISjIVvvOTQ43WpFeKc1DFrKa
username = ceilometer
project_name = service
project_domain_id = default
user_domain_id = default
auth_type = password
interface = internal
cafile =

[oslo_messaging_notifications]
transport_url = rabbit://openstack:pY4CVoHILUo18qUzra4gTRRvyZXWPZoDYcNUPXBj@192.168.99.91:5672//

[oslo_messaging_rabbit]
heartbeat_in_pthread = false
rabbit_quorum_queue = true

[cache]
backend = oslo_cache.memcache_pool
enabled = True
memcache_servers = 192.168.99.91:11211

